name       : gromacs
version    : '2020'
release    : 5
source     :
    - https://ftp.gromacs.org/pub/gromacs/gromacs-2020.tar.gz : 477e56142b3dcd9cb61b8f67b24a55760b04d1655e8684f979a75a5eec40ba01
license    : LGPL-2.1
component  : office.scientific
summary    : GROMACS is a versatile package to perform molecular dynamics
description: |
    GROMACS is a versatile package to perform molecular dynamics, i.e. simulate the Newtonian equations of motion for systems with hundreds to millions of particles.
builddeps  :
    - pkgconfig(fftw3f)
    - pkgconfig(openblas)
    - pkgconfig(x11)
setup      : |
    %cmake -DGMX_SIMD=SSE2 \
           -DGMX_X11=1
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
